#!/bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 1
bspc config split_ratio 0.5

bspc rule -a "cheatsheet_peek" state=floating border=off fullscreen=on focus=on
pgrep -x flameshot >/dev/null || flameshot &

~/.config/polybar/launch.sh &
